import yogas from "../../images/yogas.jpg";
import mental from "../../images/mental.jpg";
import sportss from "../../images/sportss.jpg";

export const blogData = [
  {
    "id": 1,
    "title": "Rising need for counselling",
    "description": "<p>Through counseling, a person can understand the problem affecting their life and they can come up with some solution. The main thing about which people need to get aware is about being aware of their negative emotions instead of neglecting them they should try to apply ways to cope with them.</p> <p>One can cope with personal life problems such as family counseling, couple counseling, relationship counseling, and individual counseling. There are other areas like employee counseling, sports counseling, student counseling, and many more. There are employees in the companies who are stressed due to their work and somehow it affects his/ her life relations which results in a poor relationship with family and leads to low productivity at work. For example, if someone is not in a good mood due to a fight with a wife/husband then it will affect them in their office work, and he/ she will face stress and load during work which in turn will affect the productivity of work.</p><p>Nowadays people are facing depression, anxiety, stress, and tension for which counseling can be helpful for people to come up with it.</p><p>Hence, it’s high time for people to understand the concept of counseling and to go to a therapist or counselor whenever they feel the need for it instead of neglecting it.</p>",
    "category": "Therapy",
    "img": yogas,
    "imgPara": "It is very important to understand the meaning of counseling as people are not aware of it. Meaning of counseling: Counselling is to assist someone to solve their personal or professional or any other problem on their own. Counseling is something that can be for a person having day-to-day life problems as well as someone who has some mental health issue. In today’s fast world people are running here and there to earn money, to settle their lives, to be number one in the competition which is important and there is no doubt about that but somewhere they forget about themselves because, in the end, we are humans! So, we need to think about things that give us happiness and worries, tension, and stress in our life. Usually, people neglect and don’t think much about things that indirectly or directly affect their personal and professional life at times.",
  },
  {
    "id": 2,
    "title": "Ways to prevent Suicidal thoughts",
    "description": "<p> <b>Below are some of the warning signs of suicide</b> </p> <p> Noticeable changes in eating, sleeping habits, and personal hygiene </p> <p> Talking about suicide and giving hints about suicide, expressing a strong wish to die or a desire to kill someone else. </p> <p>Frequent change in mood – depressed mood or rage anger.</p> <p>Obsession with death</p> <p>Isolation and withdrawal from social situations.</p> <p>Feeling depressed, sad, anxious, inner tension.</p> <p>Increased alcohol or drug abuse.</p> <p> The most important are Do’s and Don’ts while dealing with suicidal tendencies. </p> <p> <b>Do’s</b> </p> <p> <b>Be yourself: </b> let the other person know you care, and that he/ she is not alone </p> <p> <b>Listen: </b>let the suicidal person unload his feelings, and thoughts, and let him/ her ventilate their anger, no matter how negative the conversation seems just let them speak. </p> <p> <b>Be sympathetic: </b>one should be calm, non-judgmental, accepting, and patient while listening to the suicidal person. </p> <p> <b>Offer hope to him/her: </b>let the person know that you are there for them whenever they feel like talking and assure them that the suicidal thoughts or feelings are temporary and there is nothing to feel shame about it for seeking help from someone. </p> <p> <b>Take the person seriously: </b>if the person mentions things like “I am so depressed, I am done with this, I can’t go on.” Ask questions to that person like “Are you having thoughts of suicide?”. In a way, you are showing that you are concerned about that person, and you take them seriously and it is perfectly ok for them to share their pain with you. </p> <br /> <p> <b>Don’ts</b> </p> <p> <b>Never argue with a suicidal person: </b>don’t indulge in any sort of argument when the person is having a suicidal tendency. </p> <p> <b>Act shocked: </b>don’t lecture the suicidal person about the value of life or say that suicide is wrong especially when the person is on the edge of committing suicide because at that time nothing is right or wrong for the suicidal person, instead tell them to hold back the thought of suicide and talk about what is going on in mind before taking the step of suicide. </p> <p> <b>Promise confidentiality: </b>never promise the suicidal person about keeping their secrecy as the person is at the stake of life and you might the help of a professional mental health counselor and you need to tell them about the case of the person. </p> <p> <b>Don’t try to offer ways to fix the problems: </b>don’t just start giving advice or don’t make them feel like they must justify their suicidal feelings. </p>",
    "category": "Mental health",
    "img": mental,
    "imgPara": "It is very important to know a little bit about suicide and suicidal thoughts before we directly jump onto the ways of preventing suicidal thoughts. Nowadays we read and hear about people committing suicide more frequently than before. Seeing the news of someone jumping in the river to those hanging themselves on the fan. Many such individuals have taken their lives. There can be many causes or say reasons behind committing suicide like rejection from loved ones, psychological disorder, emotionally disturbed, feeling of guilt, a victim of sexual or physical abuse, loss of hope in life, loneliness, financial burden, disturbed family, stress, depression, and many more.",
  },
  {
    "id": 3,
    "title": "Effects of Covid -19 on people’s lives.",
    "description": "<p>Many people have gone through depression because of isolation in covid-19 and other causes like loosening jobs, lack of socialization, and death of near ones and dear ones in covid. Though people used to face anxiety and depression before covid also but, during the covid-19 period, there was a rise in the number of people facing mental health problems such as anxiety, depression, and suicidal- tendencies</p><p> There are certain positive things that we must notice such as nowadays people are wearing masks, they wash their hands properly before and after eating food, many of them have started doing their house chores, people got to understand the importance of family and friends, the importance of maintaining physical and mental health, ideas of starting their startup for being financially independent.</p><p> To make it from long to short there are pros and cons, but it is up to us whether we want to pick up the cons and get stuck with them or move ahead by picking up the pros.</p>",
    "category": "Physical health",
    "img": sportss,
    "imgPara": "When we talk about the life of people before the pandemic, it is very different from now. When we think about a pandemic, the first thing that comes to mind is a lockdown in the whole country, the deaths of so many people, and all those traumatized things that have affected us emotionally and psychologically.",
  },
]
